### ISSUE TITLE
_exists function 

### ISSUE THREAD

**Issue by pale-aura** [estarriolvetch/ERC721Psi#10]
![image](https://user-images.githubusercontent.com/92485969/176784652-ca9f3f51-6fd5-47e3-abe6-b71104eba40e.png)

Shouldn't this be tokenId <= _minted instead of just tokenId < _minted ?

If I mint only 1 token, the function will return false for _exists(1).

Also breaks if I pass in tokenId of 0.

**Comment by estarriolvetch** [comment]
The tokenId starts with zero. It's why it is less.

What do you mean by "Also breaks if I pass in tokenId of 0."?

-------- Original Message --------

**Comment by pale-aura** [comment]
Oh ok I see now. Thanks for clarifying.

What was the reason for starting token id at 0? I think that could be a deal breaker for a lot of projects because it creates a weird user experience.

**Comment by estarriolvetch** [comment]
It's a more natural indexing option in coding, and the original ERC721A also uses that.

I am thinking of adding support for changing starting index, but I haven't get a chance to do that. Let me know if you are interested in sending a PR.

-------- Original Message --------
