### ISSUE TITLE
balanceOf can run out of gas

### ISSUE THREAD

**Issue by m4nuC** [estarriolvetch/ERC721Psi#11]
If the current supply gets very high (say 50k+) then `balanceOf` call potentially run out of gas. Infura for instance caps `eth_call` to 60Millions gas. 

What are your thoughts on this issue ?

**Comment by estarriolvetch** [comment]
You are absolutely correct. If you need more than 6M gas, you can use alchemy which offers 300 million gas.

On the other hand, you may consider just using the NFT API from Alchemy or quicknode directly if you have a big collection.

If you really need balalceOf​, you can also use the AddressData​ extension.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
