### ISSUE TITLE
Gas savings for mint

### ISSUE THREAD

**Issue by nidhhoggr** [estarriolvetch/ERC721Psi#18]
The following changes improved the gas savings. gas differences are explained in the report diffs.

https://github.com/nidhhoggr/ERC721Psi/commit/752fcd800ca983cb829b5d149345b2f8ce598d0e

**Comment by estarriolvetch** [comment]
LGTM! Can you isolate the changes to a new PR?

**Comment by nidhhoggr** [comment]
Will do.

**Comment by nidhhoggr** [comment]
Sorry for all the pull requests, I kept forgetting to merge into v0.8 and not main... #23 should be good.
