### ISSUE TITLE
minting function with specific tokenID intervals (1-200, 200-400) based off a function "tier" argument (1 or 2)

### ISSUE THREAD

**Issue by devgodeth** [estarriolvetch/ERC721Psi#8]
Would it be possible to have a `mint` function that randomizes the tokenID of the mint between a certain number interval (1-200, 200-400) depending on the function argument `uint256 tier` (would just be 1 or 2). 

This is because of a tier system, and the metadata's are uploaded randomly, but also in a specific fashion to ensure specific images are matching their tier. So I'm trying to make Psi work with this, instead of just using ERC721 for the tier system. 

I know that the tokenID currently can't be specified due to the batch minting and randomness, but if I could at least specify the interval in which the tokenID's may be randomized in between, depending on the tier chosen, this would work. 

Oh.... and my current ERC721 implementation will be updating the baseURI at a later date for a reveal... but if I could integrate the `RandomSeedReveal`, while being able to choose the interval for the tokenID's based off the tier during `mint`, everything would work handsomely.

Thank you 谢谢 🤝

**Comment by estarriolvetch** [comment]
Not sure how to make tier works though. Like ERC721A, ERC721Psi's token id needs to match a specific order.

However, for randomized token ID mapping, I have a unannounced project to solve this problem.

Please check here: https://github.com/estarriolvetch/fpe-mapping

I haven't documented it yet, so you might need to figure out how to use it from the test cases.

**Comment by devgodeth** [comment]
I see... really i just need to cap the interval of the random number being generated for the tokenID.. checking that link out
